### ISSUE TITLE
Typo on https://github.com/solliancenet/MCW-innovate-modernize-apps-with-data-ai/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Innovate%20and%20Modernize%20Apps%20with%20Data%20and%20AI.md#requirements

### ISSUE THREAD

**Issue by joaobi** [solliancenet/MCW-innovate-modernize-apps-with-data-ai#10]
The page https://github.com/solliancenet/MCW-innovate-modernize-apps-with-data-ai/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Innovate%20and%20Modernize%20Apps%20with%20Data%20and%20AI.md#requirements

Typo: Install the Azure Machine **Leraning** SDK for Python.

**Comment by feaselkl** [comment]
Thank you.  We will correct this.
