### ISSUE TITLE
The Azure Synapse resource provider (Microsoft.Synapse) needs to be registered with the selected subscription.

### ISSUE THREAD

**Issue by joaobi** [solliancenet/MCW-innovate-modernize-apps-with-data-ai#11]
You might need to give instructions on how to register the Synapse Resource Provider if not already done ahead of "Task 9: Provision an Azure Synapse Analytics workspace".

I got the error: "The Azure Synapse resource provider (Microsoft.Synapse) needs to be registered with the selected subscription." when I just followed the instructions

**Comment by feaselkl** [comment]
Thank you for the feedback.  We will add a note pointing out the registration link for first-time Synapse users.
