### ISSUE TITLE
MCW Draft Review and SME Feedback

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [solliancenet/MCW-innovate-modernize-apps-with-data-ai#8]
Please leave feedback, comments, and questions for our authors inside this GitHub issue.

**Comment by nchandhi** [comment]
Exercise 2: Use Azure Synapse Analytics to train and register a predictive maintenance model
(This work needs to move to AML studio).

Background: The direction for field is that all ML work orchestration to be done in Azure Machine Learning Studio and not from Synapse workspace notebooks. This is enforced by BG for all the assets we are creating in FY21. So we need to create all the ML notebooks in Azure Machine Learning. We also need to remove the ML notebooks from Synapse Workspace. I can share more details on a call if needed.

**Comment by timahenning** [comment]
This MCW project is the one of the last FY20 projects.  I spoke to the developers to get a sense of the time required to remove the notebook from Synapse notebook from Exercise 2 and create it in AML Studio.  It would take about 5 - 8 hours to complete.  This type of change goes beyond a small change and should be covered a test fix.

**Comment by timahenning** [comment]
A quick meeting to review the details would be very helpful.

**Comment by GaryHopeMS** [comment]
Code in Exercise 6 code refers to a config variable named "modernizeapp_DOCUMENTDB" please make reference to Cosmos DB with the new name rather than the older DOCUMENTDB naming throughout.

**Comment by GaryHopeMS** [comment]
Can we add a Task 4 in Exercise 7 to migrate the function in Exercise 4 Task 3 to using Azure Change Feed Processor in an AKS container. Illustrating the ability to scale up AKS and change feed processor to automatically provision additional processors per partition. Partitioning of Cosmos DB contain would need to be appropriate (haven't checked).

**Comment by GaryHopeMS** [comment]
Add additional diagram to illustrate which services are containerized and run under AKS

**Comment by nchandhi** [comment]
Exercise 4 Task3: Fails with below error on build ( also see screenshot)

ProcessTelemetryEvents.cs(88,16): error CS1061: 'TelemetryOutput' does not contain a definition for 'machineid' and no accessible extension method 'machineid' accepting a first argument of type 'TelemetryOutput' could be found (are you missing a using directive or an assembly reference?) [C:\Temp\AzureFunctions\AzureFunctions.csproj]
ProcessTelemetryEvents.cs(124,17): error CS0117: 'TelemetryOutput' does not contain a definition for 'machineid' [C:\Temp\AzureFunctions\AzureFunctions.csproj]
ProcessTelemetryEvents.cs(124,32): error CS1061: 'TelemetryOutput' does not contain a definition for 'machineid' and no accessible extension method 'machineid' accepting a first argument of type 'TelemetryOutput' could be found (are you missing a using directive or an assembly reference?) 
[C:\Temp\AzureFunctions\AzureFunctions.csproj]
ProcessTelemetryEvents.cs(162,66): error CS1061: 'TelemetryOutput' does not contain a definition for 'machineid' and no accessible extension method 'machineid' accepting a first argument of type 'TelemetryOutput' could be found (are you missing a using directive or an assembly reference?) 
[C:\Temp\AzureFunctions\AzureFunctions.csproj]

![image](https://user-images.githubusercontent.com/22228486/90302974-dd574e80-de5e-11ea-9cb2-f158e9d6ed72.png)

**Comment by feaselkl** [comment]
@nchandhi I have a fix for that incoming--thank you for pointing that out.  Looks like I failed to copy over a change from my local Function class to the guide.  The correction goes back to Exercise 3, Task 3, the WriteEventsToTelemetryContainer.cs file.  If you want to move forward as I get the pull request together, the changes to make are as follows:

Line 39 of the WriteEventsToTelemetryContainer.cs file should currently read "public string event_type {get; set;}".  Above that line, add "public int machineid {get; set;}" to add the reference.

Then, on line 71 it should read "id = System.Guid.NewGuid().ToString()," and below that line add a new line with "machineid = machineid ?? 0,"

Those two changes should fix the issue you're seeing and let you progress further.

**Comment by joelhulen** [comment]
Closing since the content has long since been published under the official Microsoft repo.
